#!/usr/bin/env python
"""
Market Analysis Workflow CLI

This CLI orchestrates the market analysis workflow which:
1. Fetches market data including GDP, inflation, unemployment, and bond yields
2. Generates market charts and visualizations
3. Creates comprehensive market reports with analysis
4. Integrates with the central dashboard

The workflow is designed to provide market snapshots and analysis
through the following components:
- workflows/market/market_data.py: Data fetching and processing
- workflows/market/market_report_generator.py: Report generation
- workflows/market/market_chart_generator.py: Chart creation
- workflows/market/market_report.html: Report template

Helper Functions and Utilities:
-----------------------------
1. BaseFetcher (workflows/base_fetcher.py):
   - Provides caching functionality for data fetching
   - Handles cache directory management
   - Implements force refresh and cache expiration logic
   - Methods: _load_from_cache(), _save_to_cache(), _should_use_cache()

2. Base Layout (server/base_layout.html):
   - Provides the base HTML template for reports
   - Includes dark mode support
   - Integrates Tailwind CSS and Font Awesome
   - Defines common header and footer structure
   - Supports custom blocks for content, styles, and scripts

3. Metadata Generator (workflows/metadata_generator.py):
   - Generates standardized metadata for reports
   - Handles different report types (backtest, comparison)
   - Saves metadata to JSON files
   - Tracks creation timestamps and report paths

4. Utils Directory (/utils):
   - Contains utility functions and helpers
   - Includes data fetchers for various market data
   - Provides configuration management
   - Handles most recent data tracking
   - Contains dashboard generation utilities

Dashboard Generation and Usage:
-----------------------------
- This CLI generates a market analysis report and saves it to the results directory.
- The dashboard (index.html) is generated and served by server/report_server.py, not by this CLI.
- To view and serve the dashboard, run: python server/report_server.py
- The dashboard will automatically pick up new reports generated by this CLI.

Usage:
    python market_workflow_cli.py [--force-refresh] [--output-dir path/to/dir]
"""

import argparse
import logging
from server.services.report_workflow_service import generate_market_report as _service_generate

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description='Generate market analysis report')
    
    parser.add_argument('--output-dir', type=str, default='public/results',
                      help='Directory to save the report (default: public/results)')
    parser.add_argument('--force-refresh', action='store_true', default=False,
                      help='Force refresh of data (bypass cache)')
    
    return parser.parse_args()

def create_market_report(args) -> str:
    """Generate the market analysis report — delegates to the report workflow service."""
    logger.info("Market report generation requested via CLI")
    return _service_generate(
        output_dir=args.output_dir,
        force_refresh=args.force_refresh,
    )

def run_market_report(output_dir='public/results', force_refresh=False):
    """Generate the market analysis report. Returns the report path."""
    args = argparse.Namespace(output_dir=output_dir, force_refresh=force_refresh)
    return create_market_report(args)

def main():
    """Main function to run the market analysis report."""
    args = parse_args()
    try:
        report_path = create_market_report(args)
        print(f"Market report generated at: {report_path}")
        print("Or access it via: http://localhost:8000/ (if server is already running)")
    except Exception as e:
        logger.error(f"Failed to generate market report: {e}", exc_info=True)
        exit(1)

if __name__ == "__main__":
    main() 